### ISSUE TITLE
any alternative of method "collect" in chatroom tutorial?

### ISSUE THREAD

**Issue by davidjuin0519** [boazsegev/plezi#12]
I was making a chatroom app with plezi and just found that the `collect` method had been deprecated...
Just wondering if there is any alternatives of this method? thanks!

**Comment by boazsegev** [comment]
The issues that guided me in removing `collect` are these main two issues:

1. `collect` required all the tasks "collected" to run sequentially in order to build an Array. This could potentially block the connection for a long time, especially when supporting large amounts of connections.

     This issue also conflicted with the idea of an event-driven architecture, where you could safely schedule events on any connection, knowing that each connection will perform only one task at a time. This design helps prevent data corruption in a multi-threaded environment (it's a thread safety design adopted from javascript and it applies only to the connection's instance data, which is intuitively considered "safe").

2. The `collect` method required that all the connections be present on the same machine, or that the machine would wait until `collect` was executed on any remote machine running the same application - thereby preventing applications using `collect` from scaling. 

     Scaling and high connection concurrency are some of the driving considerations behind Plezi's design. This is why I'm now spending time on re-writing the IO layer in C (allowing for thousands of concurrent connections).

I'm afraid that any alternative to `collect` will suffer from these two same faults :-(

I don't know what your need might be, but I would consider either:

1. storing global data on Redis (or a local registry) in a thread safe manner, as simultaneous connections might want to access and edit the data at the same time. This is similar to how the Identity API works on Plezi and you can see [an example of this solution inside Plezi's code](https://github.com/boazsegev/plezi/blob/15eb49b9114cb9d5a76fe11654f803451dc74cd8/lib/plezi/handlers/ws_identity.rb#L141-L161).

2. a different approach, which might introduce a lot of "stress" on your application (think of hundreds of thousands of concurrent connections on different machines), would be to globally `broadcast` an event that sends back `unicast` as a reply. i.e: 

```ruby
def Controller
   # ....
   def on_open
      broadcast :question, uuid
   end

   protected
   def question asker
      unicast asker, :answer, uuid, params[:name]
   end
   def answer other_conn, name
      puts "The user #{name} is connected with UUID #{other_conn}"
   end
end
```

**Comment by davidjuin0519** [comment]
Thanks for your reply! It took some time for me to figure this out...
For me, the purpose of using `collect` is that I need to access other connections. As suggested above, now I am trying to use `register_as` and `notify`. But I cannot get other connections either.

Perhaps there is a way to list connections in your design?

In order to get uuid, I am doing the following now:

```ruby
connections = ObjectSpace.each_object(Plezi::Base::WSObject).to_a.map do |connection|
  connection.cookies['rails_uuid']
end
```

Very stupid...Perhaps you can give me some suggestion to improve this...

**Comment by boazsegev** [comment]
Hi David,

I'd love to get a little more information, so that I could help you out with this.

Your temporary solution (using `ObjectSpace`) is very localized and it will prevent you from scaling your application in the future. Also, although the websocket API is stable for version 0.12.x, it's location under `Plezi::Base` isn't as stable (anything under `Base` is considered internal).

I'm wondering what's the purpose for which you want to use `collect`. For instance, what is the point of collecting the `rails_uuid` cookie data? Do you have a persistent database for users? what are you using the collected data for?

For example, if you have a persistent database for users, you can have each user register under their database's user ID (using `register_as`), this way you can send them private messages without by using `notify` with their database's user ID (using `user.id`).

Also, if everyone is chatting with everyone, a simple `broadcast` would work better then sending private messages to everyone connected...

Last, but not least, it's possible to use the `on_open` and `on_close` callbacks to have each connection add their data to some global "registry" (just remember thread safety, as concurrent connections can be opened and closed at the same time).

I'm waiting to learn more about your application's needs and design before I can give any recommendations.

**Comment by davidjuin0519** [comment]
Thank you for your response and I do learn a lot from you. I would like to tell you more about my project.
Just one thing I need to figure out before moving on:

> you can have each user register under their database's user ID (using register_as), this way you can send them private messages without by using notify with their database's user ID (using user.id).

In this quote, you mentioned that I could either use `register_as` or `notify` to send private message. 

1. However, I have no idea how to do it with `register_as`(perhaps I missed the doc again...).

2. Also, while I used `notify`, some error message pops out:
```
ERROR -- : Notification recieved but no method can handle it - dump:
```
Perhaps you can show me the proper way to utilize `notify`?

Thank you!

**Comment by boazsegev** [comment]
Here's a short demo.

In this demo, I don't have a database, so I will use the session ID to uniquely identify each client.

If you're using Rails, you should replace the session ID with the User ID, this way it will be synced with your application user's database.

```ruby
require 'plezi'

class MyController
   #...
   def index
       "Test me on http://www.websocket.org/echo.html"
   end
   def on_open
       # # You should probably use:
       # user = authenticate_user
       # close unless user
       # register_as user.id
       register_as session.id
   end
   def on_message data
      # we will send a notification for ourselves, although it's not a great example
       notify session.id, :got_chat_message, "Me", data
   end

   protected

   def got_chat_message from, msg
       # handle your event here...
       write({event: :chat, from: from, data: msg}.to_json)
   end
end

route '/', MyController
exit
```

You can test this code snippet on http://www.websocket.org/echo.html - remember to set the server's location to `ws://localhost:3000/`

Notice, that the **`notify` doesn't send data to directly to the websocket** - it sends a message to the other connection's controller - this message is routed to the **controller's method**.

In this case, I defined an event handler called `got_chat_message` and sent that event to the registered connection's controller (which was the same controller on this demo).

**Comment by davidjuin0519** [comment]
Hi Bo, 
Thank you for your helpful demo. I already implement this into my app. 
In your demo, there is one line: 
```
user = authenticate_user
```
Is `authenticate_user` a built-in method? If yes, how should I utilize it? Thank you!

**Comment by boazsegev** [comment]
Hi Chiu,
The `authenticate_user` method is a place-holder. it's not implemented for you - you need to decide how to implement it.

But you can have a look at (or you can use) [the OAuth controller](https://github.com/boazsegev/plezi/blob/f31ac440dd710b9994b9b6a183fa62623392378d/lib/plezi/oauth/auth_controller.rb) as an example for writing an authentication layer that can be used to add session data or perform authentication actions.

**Comment by boazsegev** [comment]
Hi Chiu

I'm closing this issue both because I think it's been covered and because it's becoming less valid with the upcoming release of Plezi 0.14.0, which is a total rewrite, for Plezi as well as Iodine
