### ISSUE TITLE
"rails generate controller" triggers iodine server to start

### ISSUE THREAD

**Issue by davidjuin0519** [boazsegev/plezi#13]
Every time I use `rails g controller` command, it will inevitably trigger iodine server to start...Any way to avoid this from happening? Thanks again for the help!

**Comment by boazsegev** [comment]
Hmmm... I did you use [the code snippet suggested in the documentation](http://www.plezi.io/docs/rake#with-rails)?

As a sidenote:

I think the autostart feature is causing more confusion then it should. I'm considering to drop it, or restrict it in Plezi 0.13.0 (i.e., only autostart if routes were defined)...

The new version is in the works and it will include major updates for better performance, scalability and inter-operatability (I'm now rewriting the core server in C, leveraging `kqueue` and `epoll` for a major performance and concurrency boost)... I will address this issue as well and I'd love to have your feedback as well.

**Comment by davidjuin0519** [comment]
I missed this part of doc... Very appreciate your response!
But unfortunately I cannot fix this by following the suggested solution.
Here is the code:
```ruby
#config/application.rb
require File.expand_path('../boot', __FILE__)

require 'rails/all'
Bundler.require(*Rails.groups)

module my_app
  class Application < Rails::Application
    config.before_initialize do
      if Rails.const_defined?('API') || Rails.const_defined?('Console')
        Iodine.protocol = nil
      end
    end
  end
end
```
Is there anything wrong with this snippet of code? Thanks for your help!

**Comment by boazsegev** [comment]
Hi,

I'm not so sure why it's not working for you.

Looking to at JokerCatz's code on issue #10 , it seems that he he put the Plezi code in a folder where it wasn't being Auto-Loaded, so that it had to be required manually (either before the `Iodine.protocol=nil` or within the `else`. This way, any changes made by requiring the application are undone when the following line is called: `Iodine.protocol = nil`.

Also, I'm just wondering...

Why did you choose to wrap the code within a `config.before_initialize` block? Why not put the code in the root level of the file? 

I'll try to open a Rails project and see if it works for me, but I'll do that a bit later - I have a busy day today.

**Comment by davidjuin0519** [comment]
I fixed my code to:
```ruby

require File.expand_path('../boot', __FILE__)
require 'rails/all'
Bundler.require(*Rails.groups)

if Rails.const_defined?('API') || Rails.const_defined?('Console')
  Iodine.protocol = nil
elsif Rails.const_defined?('Server')
  # require_relative  '../app/sync/plezi_sync.rb'
end

module Chatty
  class Application < Rails::Application
  end
end
```
but still not working...And also I am wondering what is 'root level' meant? Thanks!

**Comment by boazsegev** [comment]
I'm closing this, as the next release (coming soon) is a total rewrite, for Plezi as well as Iodine and the auto-start feature.

If the new version (v. 0.14.0, unreleased just yet) invokes a similar issue, feel free to open a new issue.

Thanks.
