### ISSUE TITLE
Long polling example

### ISSUE THREAD

**Issue by bluegod** [boazsegev/plezi#4]
Hi,

I would like to use plezi as a long polling HTTP server, which means that I don't want to use it as a fallback from websockets but purely a long polling web server. Are there any example on how to accomplish this?

Also, would it be possible to use these capabilities inside an existing rack/grape ruby app? Migrating from rack would be ok but would need to preserve Grape.

**Comment by boazsegev** [comment]
Hi,

For a demo about RESTful Plezi controllers, you can look over [the code for the StubRESTCtrl controller](https://github.com/boazsegev/plezi/blob/master/lib/plezi/handlers/stubs.rb), which is just a stub used for testing.

Using Plezi for long pulling, without web socket support, is super easy.

Here's an outline (a full-fledged Plezi app would look very different):

```ruby

class MyController
      # every request that routes to this controller will create a new instance
      def initialize
      end

      # called when request is GET and params\[:id] isn't defined
      def index
            "Hello World!"
      end

      # called when request is GET and params\[:id] exists
      def show
            "nothing to show for id - #{params[:id]} - with parameters: #{params.to_s}"
      end

      # called when request is GET and params\[:id] == "new" (used for the "create new object" form).
      def new
            "Should we make something new?"
      end

      # called when request is POST or PUT and params\[:id] isn't defined or params\[:id] == "new" 
      def save
            "save called - creating a new object."
      end

      # called when request is POST or PUT and params\[:id] exists and isn't "new"
      def update
            "update called - updating #{params[:id]}"
      end

      # called when request is DELETE (or params["_method"] == 'delete') and request.params\[:id] exists
      def delete
            "delete called - deleting object #{params[:id]}"
      end
end
require 'plezi'
require 'pathname'

Root = Pathname.new(File.dirname(__FILE__)).expand_path

listen # root: Root.join('public').to_s,
       # assets: Root.join('assets').to_s,
       # assets_public: '/assets',
       # templates: Root.join('app','views').to_s,
       # ssl: false

route '/(:id)/(:value)', MyController

exit #only if using terminal
```

Now try visiting:

* [http://localhost]()

* [http://localhost:3000/new](http://localhost:3000/new)

* [http://localhost:3000/1](* [http://localhost:3000/1)

* [http://localhost:3000/1/a%20random%20value](http://localhost:3000/1/a%20random%20value)

* [http://localhost:3000/1?method=_delete](http://localhost:3000/1?method=_delete)


As to Rack and Grape:

Plezi isn't built to be Rack compatible - although it has a [Rack adaptor](https://github.com/boazsegev/plezi/blob/master/lib/plezi/base/rack_app.rb) for testing, Plezi is a Rack **alternative**.

I'm sorry to say that since Grape depends on Rack, Plezi will be an alternative to Grape and these two platforms will not be compatible.

Good Luck!
